name = "gleamfolio"
version = "0.1.0"

# Fill out these fields if you intend to generate HTML documentation or publish
# your project to the Hex package manager.
#
# licences = ["Apache-2.0"]
# description = "A Gleam library..."
# repository = { type = "github", user = "username", repo = "project" }
# links = [{ title = "Website", href = "https://gleam.run" }]

[dependencies]
gleam_stdlib = "0.37.0"
gleam_erlang = ">= 0.25.0 and < 1.0.0"
gleam_json = "~> 0.5"
nakai = ">= 0.11.0 and < 1.0.0"
gleam_http = "~> 3.0"
gleam_cowboy = "~> 0.4"
wisp = ">= 0.14.0 and < 1.0.0"
mist = ">= 1.0.0 and < 2.0.0"

[dev-dependencies]
gleeunit = ">= 1.1.2 and < 2.0.0"
